### PR TITLE
Fix #914

### LINKED ISSUE #914: Missing rel="noreferrer noopener" for links opening in new tab/window
#### Steps to reproduce

Add a link in md file.

#### What is current behaviour

The default configuration opens a link in new tab/window. Missing rel="noreferrer noopener".

#### What is the expected behaviour
Don't we need to add rel="noreferrer noopener"?

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: NA
- Node.js version: NA
- npm/yarn version: NA
- Browser version: NA
- Docsify version: 4.9.4
- Docsify plugins: NA

### PR DESCRIPTION
**Pull request by vkallore**
**Summary**
Fixes #914 
Had raiesed an issue #914 on _missing rel="noreferrer noopener" for links opening in new tab/window_ and done the fix with 'noopener' for links with `_blank`. Thought not to add 'noreferrer' as it might be useful for referrer info.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [x] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

---

* [ ] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by anikethsaha** [comment]
the motive is to stop opening new tabs right ?
it can be done using `_self` as well in the target.

Anything extra this is doing ?

**Comment by vkallore** [comment]
Its not to prevent opening in new tab. Read about the risk of not adding it [here](https://stackoverflow.com/a/50709760/1467458)

**Comment by anikethsaha** [comment]
> Its not to prevent opening in new tab. Read about the risk of not adding it [here](https://stackoverflow.com/a/50709760/1467458)

ahh...make sense. What is the behavior of this PR when externallinktarget is `_blank` and `_self` ?

**Comment by vkallore** [comment]
As you can see in this PR commit #4769018, if the dev forgot to add the `externalLinkRel`, script will default it to `'noopener'` (also read the PR summary). Dev is also allowed to add as required (empty or different as per demands).

Does it make sense?

**Comment by anikethsaha** [comment]
I read the description already. What I was asking is whats the behavior of having both `externalLinkRel` and `externalLinktarget` ?

**Comment by vkallore** [comment]
Well, its required only for `_blank`. It has no effect if any other config value found for `linkTarget`.

**Comment by anikethsaha** [comment]
SO if `_blank` is provided, and this options is set to noopener (which is by default)` so the blank wont wok right ?

**Comment by vkallore** [comment]
`_blank` continues to work as expected. Only addition is `... rel="blah..."...` for the `<a>` tags.

**Comment by anikethsaha** [comment]
ohh.....I got it. `noopener` is for stopping the referer headers to pass.

Ok this is a valid fix.

Could You rebase and fix the conflicts. And then we are good to go 👍

**Comment by vkallore** [comment]
Resolved the conflicts.

**Pull request merged**
