### PR TITLE
Fix #865

### LINKED ISSUE #865: Embedded files doesn't resolve relative links
## Bug Report

Docsify doesn't resolve relative links in embedded markdown files correctly. Whenever MD file contains any relative link instead of file content user just gets `Not found 404` error.

#### Steps to reproduce
`README.md`
```markdown
[Task](./task/README.md ':include')
```

`task/README.md`
```markdown
# Crossword:

On the last page you found a weird crossword puzzle. Perhaps it reveals a flag for you.

[crosswords.png](./crosswords.png ':ignore')
```
`task/crosswords.png`

#### What is current behaviour

Link to `crosswords.png` points to `/crosswords.png`

#### What is the expected behaviour

Link to `crosswords.png` should point to `/task/crosswords.png`

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Ubuntu 16.04
- Node.js version: v10.15.3
- npm/yarn version: 6.4.1
- Browser version: 74.0.3729.169
- Docsify version: 4.9.4
- Docsify plugins: N/A

### PR DESCRIPTION
**Pull request by aenniw**
fixes #865 

Signed-off-by: Martin Mihálek <aenniw@gmail.com>

**Summary**

Added relative to absolute path resolving in embeded mardown files for links like so:
```markdown
[file.txt](./file.txt)
```

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome 74.0.3729.169
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

---

* [ ] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by aenniw** [comment]
Addresses #865

**Comment by anikethsaha** [comment]
We need to add tests first in this project then we will check if it's breaking or conflicting any other links

**Comment by dellagustin-sap** [comment]
Hi all, I am also experiencing this issue.
For taking our own decision on whether to document a workaround in the page our trying to apply a fix (that would introduce for us technical debt), I would like to ask if an estimated timeframe for integrating this PR could be provided.

BR,
Guilherme.

**Comment by anikethsaha** [comment]
@aenniw please rebase and resolve the conflicts.
also change the commit message. make it more detailed in order to fit better for changlog

**Comment by aenniw** [comment]
Rebased

**Comment by Jack-Works** [comment]
Still happened in 4.11.2, example: links in //jack-works.github.io/bayesian-conspiracy/#/./projects/2019/holoflows-kit.md

**Pull request merged**
