### PR TITLE
docs: Removal of flags for language choice drop-down

### PR DESCRIPTION
**Pull request by akshaybhinge19**
## Summary
Country specific flags should not be associated with language choices.
Solution: List of languages without flags

## Related issue, if any:
#2458

## What kind of change does this PR introduce?
Feature

## For any code change,

- [ ] Related documentation has been updated, if needed
- [x] Related tests have been added or updated, if needed

## Does this PR introduce a breaking change?

No

## Tested in the following browsers:

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge

### CODE REVIEW

**Review by Koooooo-7 — COMMENTED** [review]
Hi @akshaybhinge19 , thx for your contribution.
As I mentioned, we do the translation refinement for the v5 release now.
This change gonna be suspended for now.

**Comment by akshaybhinge19** [comment]
> Hi @akshaybhinge19 , thx for your contribution. As I mentioned, we do the translation refinement for the v5 release now. This change gonna be suspended for now.

@Koooooo-7 thanks for the update, sorry I misunderstood that as it is under 5.x milestone. can we update this ?

image

**Comment by sy-records** [comment]
Thank you for your contribution.
I've set it as a draft for now and will merge it in when we're sure.

**Comment by jhildenbiddle** [comment]
@sy-records @Koooooo-7 --

I think we can safely merge this PR. It's just removing flag emojis. The changes will be merged to `develop` which already has v5-related doc updates, so we won't merge `develop` into `main` until v5 is ready anyway.

**Review by sy-records — APPROVED** [review]

**Pull request merged**
