### PR TITLE
Fix scroll to page top

### PR DESCRIPTION
**Pull request by bashkirtsevich**
Update navigation feature. Scroll page to top, when user click on nav node (lvl 1 header in navigator).

Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you are merging your commits to `master` branch.
* [ ] Add some descriptions and refer relative issues for you PR.
* [ ] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by bashkirtsevich** [comment]
Also may be should add `scrollTo(null)` [here](https://github.com/docsifyjs/docsify/blob/master/src/core/event/sidebar.js#L34)?

**Comment by timaschew** [comment]
Please run these commands to trigger netlify deployment for this Pull Request:
```sh
git commit --amend --no-edit
git push --force
```

**Comment by solymosi** [comment]
I think setting `auto2top` to `true` achieves the same result as this PR. As a result, this PR would essentially force-enable `auto2top` for everyone, nullifying the browser's auto scroll-restoration behavior when going back and forward in history.

I've submitted an alternative proposal in #744

**Comment by timaschew** [comment]
Closing in favor of #744 
I've started [a discussion](https://github.com/docsifyjs/docsify/pull/744#issuecomment-485263724) regarding whether `auto2top: false` make sense.

**Pull request closed without merging**
