### PR TITLE
fix: fix docsify-ignore in seach title.

### LINKED ISSUE #1867: The tags {docsify-ignore} and {docsify-ignore-all} generated wrong hash link in search result
#### Steps to reproduce

1. typed "initialize" in search input
2. click the first result
3. see the hash code of url

image

related: https://github.com/docsifyjs/docsify/issues/767 https://github.com/docsifyjs/docsify/pull/1318

#### What is current behaviour

generated wrong hash link  

#### What is the expected behaviour

generate right hash link

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[Edit 307qqv236](https://codesandbox.io/s/wonderful-kare-vken7m)

### PR DESCRIPTION
**Pull request by Koooooo-7**
## **Summary**
fix #1867 
Remove `docsify-ignore` tag in slug before generate local storage index.

## **What kind of change does this PR introduce?**

Bugfix

## **For any code change,**

- [ ] Related documentation has been updated if needed
- [ ] Related tests have been updated or tests have been added

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

## **Tested in the following browsers:**

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Review by sy-records — APPROVED** [review]
LGTM.

**Comment by csu-feizao** [comment]
hi, is there any plan to release a version recently?

**Comment by Koooooo-7** [comment]
> hi, is there any plan to release a version recently?

Hi @csu-feizao , I m working on the #1904  test stuff, after it done, I suppose release a version soon.

**Comment by Koooooo-7** [comment]
Hi @csu-feizao , FYI, a new version released.

**Comment by csu-feizao** [comment]
> Hi @csu-feizao , FYI, a new version released.

Cool!

**Pull request merged**
