### PR TITLE
docs: add stormkit as deployment platform

### PR DESCRIPTION
**Pull request by eldemcan**
## Summary

Add stormkit as deployment platform

## What kind of change does this PR introduce?

  Docs

## For any code change,

- [ ] Related documentation has been updated, if needed
- [ ] Related tests have been added or updated, if needed

## Does this PR introduce a breaking change?

No

## Tested in the following browsers:

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by paulhibbitts** [comment]
Thanks for the PR @eldemcan . Following the provided instructions resulted in a 404 error - not familiar with StormKit but usually you need to set the folder to be served to 'docs', could you please update the PR with the needed info to do that? Thank you!

**Review by paulhibbitts — COMMENTED** [review]
Looks good to me.

**Review by sy-records — APPROVED** [review]
LGTM. Thank you!

**Comment by paulhibbitts** [comment]
Thanks for merging the PR @sy-records!

**Pull request merged**
