### PR TITLE
Added filtering in sidebar for ignoreSubHeading

### PR DESCRIPTION
**Pull request by alexcambose**
Add support for `ignoreSubHeading` when `loadSidebar` is false.

### The issue

When `{docsify-ignore}` is applied on a heading, the generated sidebar still contains the header and its subheaders. When `loadSidebar` is false only the `sidebar()` method is called so the filtering needs to be inserted there. 
https://github.com/docsifyjs/docsify/blob/8cd786c9d533faa15b989f84f7ecf0d8f705a7c8/src/core/render/index.js#L93-L107
I used classic splice() method and for loops to remove the header and all it's subheaders because I saw this method being used `subSidebar()`. I was probably better to just use the `[].filter()` way but it works anyways.

---

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you are merging your commits to `master` branch.
* [x] Add some descriptions and refer relative issues for you PR.
* [x] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by timaschew** [comment]
Hey Alexandru, thanks for your contribution!  
Can you please provide some unit tests?

**Comment by alexcambose** [comment]
I would like to but i can't figure out how to get the rendered html of the sidebar in the tests file.

**Comment by timaschew** [comment]
You can rebase on my branch: [improve-test-setup](https://github.com/docsifyjs/docsify/pull/776) I've added some tests cases which should be helpful for you.

**Comment by timaschew** [comment]
Please run these commands to trigger netlify deployment for this Pull Request:
```sh
git commit --amend --no-edit
git push --force
```

**Pull request merged**
