### PR TITLE
add plugin "words countable"

### PR DESCRIPTION
**Pull request by 827652549**
This is a plugin to add word count for markdown files of docsify.

**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

---

* [ ] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by anikethsaha** [comment]
Can you please add the link to `awesome-docsify` repo instead of here cause here we dont add many as it goes a long list

**Comment by Koooooo-7** [comment]
BTW:  
code format `countable.js` and good code annotation in English for the sort of unification ours. :+1:

**Comment by 827652549** [comment]
I have formatted the code and replaced it with English annotation.thanks @Koooooo-7

**Comment by anikethsaha** [comment]
As I mentioned earlier , it has to be in `awesome-docsify` repo. 
Closing this for now. 
Please comment if anything needs to be changed in this

**Pull request closed without merging**
