### PR TITLE
Updated docs site dark and light mode with switch and redesigned search bar using docsify-darklight-theme

### PR DESCRIPTION
**Pull request by boopathikumar018**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

Updated docs site dark and light mode with switch and redesigned search bar using [docsify-darklight-theme](https://www.npmjs.com/package/docsify-darklight-theme) you can refer the docs and see full preview [here](https://boopathikumar018.github.io/docsify-darklight-theme)

# Light Mode

## before

image

## after

image

# Dark Mode

## before

image

## after 

image

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ x] A convincing reason for adding this feature
   - Theme switcher
   - Themes are customizable based on your color preferences
   - Preferences can be modified directly in window.$docsify configuration object
   - Default theme(Dark/Light) can be configured based on your needs.
   - Themes are remembered and retrieved from local storage.
   - Redesigned search box.
- [x ] Related documents have been updated
  [Documentation & Preview](https://boopathikumar018.github.io/docsify-darklight-theme/)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

---

* [ ] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by anikethsaha** [comment]
Thanks for the PR. 
This looks really good. 
But, you might have noticed we are pushing more for v5 and I dont have a ny plan to release unless it's a bug which needs fix from the core. 
So I cant really asure you when this will be merge and we may change the styling architecture for v5. 
I will put this on hold and if we are not doing major change with styling then I will merge this for v5.

**Comment by boopathikumar018** [comment]
Hi @anikethsaha since you don't know the timeline for v5 release why don't you go ahead and merge this. Because it won't affect any previous code just adding `one style-sheet` and `one script` and it will be nice to see. If styling architecture for v5 changed I am ready to refactor my code based on that. It would by nice if you merge this. Thanks

**Comment by anikethsaha** [comment]
Actually even if I merge this , I need to release (`develop` -> `master`) which I have any intention to do so. This can be considered for `v5` if no major changes comes along w.r.t styling. 
In the meantime you can fix that switcher issue mentioned in awesome-docsify repo

**Comment by boopathikumar018** [comment]
Understood thanks. Hope you seen my updated comment on awesome-docsify PR

**Comment by anikethsaha** [comment]
@boopathikumar018 I saw your repo and the preview. its still the same. the switcher issue still there. 
Also, there are some not required stuff in the repo like some google verification HTML , I dont know what is that but that is not required for a theme. or plugin

I would suggest to have a re-check in everything and each file. 
Also, your theme/plugin is quite new  and I would wait until some other placed its being used.

I am closing this for now, lets refine that and you can submit a PR with proper files and working and those bugs fixed. 
Your theme is good, the color combination which you used is fresh. good work with that 👍 

Thanks for submitting PR. 
Keep bringing new ideas and fixes to docsify 💯

**Pull request closed without merging**
