### PR TITLE
chore: sync emojis

### PR DESCRIPTION
**Pull request by sy-records**
## **Summary**

Sync GitHub emojis.

## **For any code change,**

- [ ] Related documentation has been updated if needed
- [ ] Related tests have been updated or tests have been added

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

## **Tested in the following browsers:**

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Review by Koooooo-7 — APPROVED** [review]

**Review by trusktr — APPROVED** [review]
is there another way to do this? Perhaps get them from an API?

**Comment by jhildenbiddle** [comment]
@sy-records -- 

Looks good, but I think it's worth revisiting #779 instead of continuing to manually update this list. No issue with merging this until we resolve #779.

@trusktr --

I've reopened #779 because the PR you reference as addressing the issue are unrelated.

**Review by jhildenbiddle — APPROVED** [review]

**Comment by sy-records** [comment]
I wrote a code using PHP, not a manual update, and I will add a CI later.

**Comment by jhildenbiddle** [comment]
@sy-records --

I think we should avoid making PHP a dependency for our project. This seems like a very easy thing to do in JS/Node, no?

**Comment by sy-records** [comment]
It will not become dependent, just a CI.

I will try to use js or shell for this.

**Pull request merged**
