### PR TITLE
create tableString for search fix #582

### LINKED ISSUE #582: It does not search inside tables
Hi :)

I find out that the search tool doesn't search inside a table and I have texts inside them that need to be searchable.

Is this an issue? Or is it something that I am missing?

This is my search configuration:
```
search: {
	  paths: 'auto',
	  placeholder: 'Buscar ...',
	  noData: 'No hay resultados',
	  depth: 2,
},
```
By the way, I love Docsify, it makes my life easier :))))

### PR DESCRIPTION
**Pull request by wjhrdy**
**Create Table  String for Search**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

---

* [ ] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by wjhrdy** [comment]
I think this is what you were looking for

**Comment by wjhrdy** [comment]
It doesn't create the exact same string but I think its just fine for searching to create 
cell | cell | cell |\n cell | cell | cell

rather than

| cell | cell | cell | cell | cell | cell |

**Comment by wjhrdy** [comment]
Anything else you need me to do?

**Comment by timaschew** [comment]
Can you please add a test case. I've tried your changes locally but it doesn't work.  
It doesn't enter this case`} else if (token.type === 'table'){`

**Comment by wjhrdy** [comment]
Where do I add a test case? sorry for my ignorance.

**Comment by melloware** [comment]
Any update on this?  This feature is a huge improvement for usability.

**Comment by wjhrdy** [comment]
im using it already. i just dont know where to write tests

**Comment by tandraschko** [comment]
Any update on this?

**Comment by wjhrdy** [comment]
I think it can be merged. I'm not sure what else has to be done.

**Comment by felangel** [comment]
As @timaschew mentioned you should add unit tests to validate your changes and ensure remain intact over time. I can try to help later today if you’re having trouble writing tests for the added functionality.

**Comment by anikethsaha** [comment]
Can you please provide some snapshots for these changes. I cant review this as we don't have tests to validate this.

**Comment by sy-records** [comment]
@anikethsaha Hello, can this pr fix #582 ? I also encountered this problem, or does the official have time to fix it?

**Comment by difosfor** [comment]
I'd also like to see support for searching table contents. If you need some test content, perhaps you can look at our documentation? https://docs.liveryvideo.com/web-sdk

Let me know if/how I can help.

**Comment by anikethsaha** [comment]
closed by #1015

**Comment by anikethsaha** [comment]
> I'd also like to see support for searching table contents. If you need some test content, perhaps you can look at our documentation? https://docs.liveryvideo.com/web-sdk
> 
> Let me know if/how I can help.

the PR is merged with this fix,
You can test the new build from github to see if anything is breaking in searching

**Pull request closed without merging**
