### PR TITLE
fix: ssr TypeError: Cannot read property 'indexOf' of undefined

### PR DESCRIPTION
**Pull request by DYSDF**
See this problem in issue:
https://github.com/docsifyjs/docsify/issues/704

## **For any code change,**

- [ ] Related documentation has been updated if needed
- [ ] Related tests have been updated or tests have been added

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

## **Tested in the following browsers:**

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Comment by Koooooo-7** [comment]
@xiao99xiao  Cause the SSR refactor has not set in place yet, it may be late to merge.

@trusktr  do u think we could merge it as a patch for current SSR solution?

cc @docsifyjs/reviewers

**Comment by trusktr** [comment]
Yeah, this is already fixed in my work. SSR is working, but not all things work yet. Namely we still need some special handling for plugins. Another issue I have is I haven't installed a VM for testing, the tests don't pass in my native OS. I will circle back again soon, i haven't forgotten!

**Comment by DYSDF** [comment]
[related pr](https://github.com/docsifyjs/docsify-cli/pull/152)

**Comment by sy-records** [comment]
see #2105

**Pull request closed without merging**
