### PR TITLE
Update marked to 4.2.12

### PR DESCRIPTION
**Pull request by dzsibi**
## **Summary**

Updates marked to the latest version. There were a _few_ pull requests by @snyk-bot (#1505, #1562, #1724, #1903, #1920), but due to some breaking changes in [marked 4.0.0](https://github.com/markedjs/marked/releases/tag/v4.0.0), it failed to build. I fixed the issues and all tests are green. I couldn't find any other breaking changes in terms of API and output, but since this is a jump of over 2 years worth of marked releases, it is possible that this will break something somewhere.

## **What kind of change does this PR introduce?**

Other

Dependency upgrade

## **For any code change,**

- [ ] Related documentation has been updated if needed
- [ ] Related tests have been updated or tests have been added

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

## **Related issue, if any:**

#1885 is about the ancient dependency itself. #1874 provided a workaround (inject a newer version), but was likely due to the new extension type not working with the old marked version.

## **Tested in the following browsers:**

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Review by Koooooo-7 — APPROVED** [review]
Hi @dzsibi , nice work, thx ! LGTM.

**Comment by dzsibi** [comment]
I found one more breaking change related how the search plugin handles Table tokens (`rows` was renamed to `cells`, and it is now an object).

**Comment by trusktr** [comment]
> I found one more breaking change related how the search plugin handles Table tokens (`rows` was renamed to `cells`, and it is now an object).

Nice find. We need to start a migration guide so we can document anything that breaks.

Whether or not we bump Docsify to 5.0 or keep it at 4.0 doesn't matter as much, as long as we can clearly have a written pathways for upgrade steps.

I think perhaps we can also link to marked change/migration log.

**Comment by paulhibbitts** [comment]
Thanks so much for this PR @dzsibi , I have started testing in my Docsify Starter Kits and a test build of Docsify-This (https://test.docsify-this.net).

**Comment by dzsibi** [comment]
Any progress on merging this / any additional input needed from me?

**Comment by Koooooo-7** [comment]
> Any progress on merging this / any additional input needed from me?

Hi @dzsibi , we are running this on some instances with our contributors to check if there has any breaking issues.
If everything is okay, we gonna merge it later.
Currently there is no more changes to do except we figure out if something unpredictable happens on this change.
Thx again. If we have some changes further required on this PR, we could work it with you then.

**Comment by paulhibbitts** [comment]
My tests with several Docsify instances have all gone well, so now I've updated my main https://Docsify-This.net app and will report back in the next few days with the results - so far so good!

**Comment by paulhibbitts** [comment]
Ok, I've now run the test build for 5 days on https://Docsify-This.net  and no issues have been reported nor have I seen any myself.

**Review by Koooooo-7 — APPROVED** [review]
Since there is no other issues remained now. I gonna approve it on my side.
And  we may create a new release for this  individually.

**Pull request merged**
