### PR TITLE
convert Docsify and mixins to ES classes

### PR DESCRIPTION
**Pull request by trusktr**
## **Summary**

Converts Docsify and its internal mixins to ES classes. The advantage is static typing: this change begins to allow IDEs like VS Code to know the shape of classes for type checking and intellisense, so devs can go-to-definition on methods, or see if they are passing the wrong data type (still needs work, but this is a first step).

https://user-images.githubusercontent.com/297678/145127125-5e67be37-a6c7-4428-bfad-7cbb0e5896a1.mp4

## **What kind of change does this PR introduce?**

  Refactor

## **For any code change,**

- [ ] Related documentation has been updated if needed
- [ ] Related tests have been updated or tests have been added

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

## **Tested in the following browsers:**

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Comment by trusktr** [comment]
I had to run the test three times for them to pass. That's a bit annoying.

**Comment by trusktr** [comment]
this is good to go

**Review by Koooooo-7 — APPROVED** [review]
I think It makes Docsify more readable with ES upgrade.
LGTM.

**Comment by trusktr** [comment]
Btw, if you turn on "hide whitespace" in the "files changed" tab, the diff is easier to see. Not too many actual changes besides whitespace indentation.

**Review by sy-records — APPROVED** [review]
If it doesn't affect previous users, it's fine. 
LGTM.

**Comment by trusktr** [comment]
> If it doesn't affect previous users, it's fine. LGTM.

Yep yep! Let's keep as much backwards compatibility as possible. The new Solid-SSR stuff will be compatible with v4

**Pull request merged**
