### PR TITLE
chore: docsify-ignore config polish.

### PR DESCRIPTION
**Pull request by Koooooo-7**
## **Summary**

Update the option 2 to use `docsify-ignore`.

## **What kind of change does this PR introduce?**

Docs

## **For any code change,**

- [x] Related documentation has been updated if needed
- [ ] Related tests have been updated or tests have been added

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

## **Tested in the following browsers:**

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Review by sy-records — COMMENTED** [review]
I don't think it needs to be modified.

Why do you want to modify here?

**Comment by Koooooo-7** [comment]
> I don't think it needs to be modified.
> 
> Why do you want to modify here?

We have two ways to config the ignore setting.
both `<!-- {docsify-ignore-all} -->` and `{docsify-ignore-all}` works. we should mention them all here. and the `{docsify-ignore-all}` is useful when u do not wanna meet someone html escape issue.

**Comment by sy-records** [comment]
That should add a more detailed description, now this change can be easily misinterpreted as a contextual error.

**Comment by Koooooo-7** [comment]
> That should add a more detailed description, now this change can be easily misinterpreted as a contextual error.

yep, I update it.

**Review by sy-records — APPROVED** [review]

**Pull request merged**
