### PR TITLE
chore: update vercel logo

### PR DESCRIPTION
**Pull request by sy-records**
Edit --

We just need to add the logo to the README and to the bottom of the page of the site deployed with Vercel.

### CODE REVIEW

**Comment by jhildenbiddle** [comment]
@sy-records --

I'm happy Vercel has given us a free Pro account and I understand they want us to acknowledge their support, but the "Powered by Vercel" on ever page of our docs site feels excessive. Our docs site is not "powered" by Vercel; it is powered by docsify and GitHub. We use Vercel for our PR and `develop` branch previews only (as far as I know -- correct me if I'm wrong).

My two concerns here are 1) some may potentially be confused by the logo and what it suggests, and 2) the logo is linked to what could be seen as a potentially competing platform (Next.js for documentation).

**Comment by sy-records** [comment]
Yes, that's what I thought before I didn't change the logo.

Do we specifically need a Pro account?

https://vercel.com/docs/concepts/limits/overview

If we use a personal account, we are only limited to Connecting a Project to a Git Repository?

**Comment by jhildenbiddle** [comment]
I don't think we can use a personal account simply for reason that "Hobby" accounts do not allow more than one team member.

I think this is just a matter of clarifying what the Vercel's requirements are for free open-source "Pro" accounts. We already list Vercel under a "Special Thanks" section on the repo's `README.md` file:

CleanShot 2022-03-21 at 23 08 59@2x

My gut tells me that Vercel does not expect anyone to plaster their logo all over the website and documentation. I'm sure they're happy if people do that, but it isn't a requirement (that would be pretty obnoxious). Instead, I'm guessing their providing feedback on the logo and copy *that we already have* on our docs site. My vote would be to see if 1) they are okay with us giving "thanks" just on our repo's README.md, 2) if we stay away from the "Powered by" button to avoid potential confusion, and 3) if we can (or if they'd like us to) update the copy that goes with the logo to be a little more specific and appreciative. For example:

> [Logo] Vercel has generously provided the Docsify project with Pro account for development and testing.

That may be a little verbose, but you get the idea.

**Comment by sy-records** [comment]
@jhildenbiddle You are right, Vercel for us is used for PR and branch preview, at this time I think it is possible to add their logo.
I removed it from the GitHub pages service. Let's see what the Vercel team has to say.

**Review by Koooooo-7 — APPROVED** [review]
LGTM.

**Pull request merged**
