### PR TITLE
fix: scrollToView not working properly if images exist

### PR DESCRIPTION
**Pull request by cheng-kang**
Closes: https://github.com/docsifyjs/docsify/issues/351

-----

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you are merging your commits to `master` branch.
* [x] Add some descriptions and refer relative issues for you PR.
* [x] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by dawit-elias** [comment]
Any updates on this @QingWei-Li? This fix will alleviate the confusion that people who currently read our docs experience.

**Comment by timaschew** [comment]
Please run these commands to trigger netlify deployment for this Pull Request:
```sh
git commit --amend --no-edit
git push --force
```

**Comment by timaschew** [comment]
Would be nice to have a test case for the problem which is solved by this PR

**Comment by dawitelias** [comment]
@timaschew There's a repro case at the top of this issue: https://github.com/docsifyjs/docsify/issues/351#issue-289125410.

**Comment by dawit-elias** [comment]
@timaschew There's a repro case at the top of this issue: https://github.com/docsifyjs/docsify/issues/351#issue-289125410.

**Comment by rp-applied** [comment]
Anything preventing this from being merged? Would love this change as well! :)

**Comment by timaschew** [comment]
@rp-applied a test case is still missing in this PR

**Comment by nnblack1980** [comment]
@timaschew - what's the best way to deliver a test case?

**Comment by nnblack1980** [comment]
@timaschew 

Here's a test case. If you hit this URL directly you should be scrolled to the `Test 3` section- but due to the images you see the `Test 2` section. 

https://nnblack1980.github.io/#/?id=test-3

Here's the repo: https://github.com/nnblack1980/nnblack1980.github.io

**Comment by jhildenbiddle** [comment]
Hey folks.

It's worth mentioning that while this PR may fix (I haven't tested it) `scrollToView` behavior with regards to image loading, it does not address the fact that the same issue exists for docsify plugins that modify the DOM (which can alter scroll positions by changing the content area dimensions). This bug was brought to my attention via https://github.com/jhildenbiddle/docsify-tabs/issues/8. As I mentioned in a reply to the issue:

> The short explanation is that docsify begins scrolling to the section specified in the URL before plugins (like docsify-tabs) or external content (image, video, AJAX content, etc.) have loaded. When plugins or external content can affect final page height, they also affect the final scroll position of each section. Docsify fails to account for this and scrolls to the *original* (incorrect) scroll position specified in the URL.
> 
> An actual fix would involve using [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) (and [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) as a fallback) to continuously monitor for content height changes, then scrolling (if the section has not already been scrolled to) or jumping (if the section was previously reached) to the section until a user-initiated scroll is detected. Monitoring for content height changes is the only way to detect *all* scroll position changes regardless of how or why they happen. Once a user-initiated scroll is detected, observers used to detect content changes and event listeners used to detect user-initiated scrolling can be removed so there's no left over cruft. Most importantly, this solution allows users to land on a page, have the correct section scrolled into view regardless of how content is loading above the target section.

The above solutions handles all cases (instead of just images) and it seems easier to implement that the image-only fix proposed here.

Thoughts?

**Comment by kleinjm** [comment]
Would it be possible to offer the option to disable the `scrollTo` behavior on page load? That way a custom scroll implementation can be written by those using the library

**Pull request closed without merging**
