### PR TITLE
fix: handler of A link in history router mode

### PR DESCRIPTION
**Pull request by imyelo**
`<A>` link that is nested at multilayers cannot be intercepted under
history router mode.

e.g.:
```html
<a>
  <div>
    <span>TEXT</span>
  </div>
</a>
```

We should use `closest` function to find the `<A>` link in this case.

-----

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you are merging your commits to `master` branch.
* [x] Add some descriptions and refer relative issues for you PR.
* [x] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by timaschew** [comment]
Please run these commands to trigger netlify deployment for this Pull Request:
```sh
git commit --amend --no-edit
git push --force
```

**Comment by timaschew** [comment]
the module has a dependency which doesn't work in Node.js even if the source on GitHub works, but it seems that it was not published to npm.

Funny fact there is an alternative module with the same issues. But fortunately I have npm permission to publish, so this module works in Node.js: https://www.npmjs.com/package/component-closest

Be careful, the API is a bit different (the last argument)

**Comment by jhildenbiddle** [comment]
Do we really need to add a dependency for this? Why not just bake a [polyfill](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches#Polyfill) into docsify core so it can be easily removed once docsify drops IE support?

**Comment by timaschew** [comment]
So true. We need it only for IE. So maybe some day we can even remove it.

**Comment by imyelo** [comment]
> The **closest** module has a dependency which doesn't work in Node.js even if the source on GitHub works, but it seems that it was not published to npm.
> 
> Funny fact there is an alternative module with the same issues. But fortunately I have npm permission to publish, so this module works in Node.js: https://www.npmjs.com/package/component-closest
> 
> Be careful, the API is a bit different (the last argument)

Ah! I did want to use component-closest, that I have used in [other projects](https://github.com/imyelo/docsify-pagination) before. Looks like I got mixed up.

**Comment by jhildenbiddle** [comment]
@timaschew --

I was also referring to closest.

I don't think we should be adding dependencies for third-party libraries that replace native methods unless there is a very good reason to do so. For example, consider the differences in usage for the native `Element.closest()` method vs. [component-closest](https://www.npmjs.com/package/component-closest):

```js
// Native
elm.closest('p');

// component-closest
closest(elm, 'p');
```

If we adopt component-closest and use its syntax throughout the codebase, it becomes more difficult to remove when we drop IE11. Also, those contributing to docsify may be unaware of the component-closest dependency and use the native Element.closest() method instead which could throw an error in IE if uncaught. By polyfilling Element.closest() instead of introducing a new library that accomplishes the same thing, we avoid both of these issues.

On a separate note, we can keep things nice and tidy by separating these kinds of ponyfills into a separate `legacy.js` file (or something with a similar name) and conditionally loading them based on the current browser. When the time comes to drop IE support, we simply remove this file.

**Comment by jhildenbiddle** [comment]
Another idea...

What about conditionally loading polyfills from https://polyfill.io? This might allow us to keep polyfill out of the docsify repo and still support legacy browsers like IE11 with little effort. Docsify wouldn't be as performant since it would require yet-another request, but maybe this isn't that big of an issue given IE11's market share.

@timaschew -- what do you think?

**Comment by imyelo** [comment]
> @timaschew --
> 
> I was also referring to closest.
> 
> I don't think we should be adding dependencies for third-party libraries that replace native methods unless there is a very good reason to do so. For example, consider the differences in usage for the native `Element.closest()` method vs. [component-closest](https://www.npmjs.com/package/component-closest):
> 
> ```js
> // Native
> elm.closest('p');
> 
> // component-closest
> closest(elm, 'p');
> ```
> 
> If we adopt component-closest and use its syntax throughout the codebase, it becomes more difficult to remove when we drop IE11. Also, those contributing to docsify may be unaware of the component-closest dependency and use the native Element.closest() method instead which could throw an error in IE if uncaught. By polyfilling Element.closest() instead of introducing a new library that accomplishes the same thing, we avoid both of these issues.
> 
> On a separate note, we can keep things nice and tidy by separating these kinds of ponyfills into a separate `legacy.js` file (or something with a similar name) and conditionally loading them based on the current browser. When the time comes to drop IE support, we simply remove this file.

I agree with you @jhildenbiddle ; that is why in `src/core/router/history/html5.js` I did not refer to dependencies directly but instead was forwarded by `src/core/util/dom`. Adding dependencies is not a good idea if Docsify has taken care of the closest method.

**Pull request closed without merging**
