### PR TITLE
Fix #1007 - Undefined error in search

### LINKED ISSUE #1007: Search does not work with deeply nested file structure
#### Steps to reproduce

- Create a file structure deeply nested (folder with subfolder)
- Create a custom side bar.
- Initialize Search plugin with `search: 'auto'`.
- Try to Search for content

#### What is current behaviour

Console shows the following error, search does not work.

Error

#### What is the expected behaviour

- Search does work

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: MacOS
- Browser version: Google Chrome 79.0.3945.117
- Docsify version: 4.10.2
- Docsify plugins: Search Plugin

### PR DESCRIPTION
**Pull request by Neatoro**
fixes #1007 

**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE

**Other information:**

---

* [ ] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by Neatoro** [comment]
I am currently seeing some issues in the checks, but they are not happing on my local machine. The linting seems also be caused by files that I did not touch.

**Comment by anikethsaha** [comment]
Thats fine, i will resolve it in future. Don't worry your PR is fine. I just need to make some changes then I will merge it.

**Comment by Neatoro** [comment]
@anikethsaha Thank you very much! Sounds great!

**Comment by anikethsaha** [comment]
@Neatoro could you please rebase...

**Comment by sy-records** [comment]
@anikethsaha I also have this problem, when will it be fixed?

**Comment by anikethsaha** [comment]
It will be released soon

**Pull request merged**
