### PR TITLE
Convert {docsify-ignore} and {docsify-ignore-all} to HTML comments

### LINKED ISSUE #441: {docsify-ignore-all}  should better be replaced with <!-- {docsify-ignore-all} -->
`{docsify-ignore-all}` will be rendered by GitHub or other Markdown engines, it looks very strange if someone reads docs on GitHub directly. So I suggest using `<!-- {docsify-ignore-all} -->` instead.

### PR DESCRIPTION
**Pull request by equinusocio**
Ref and close #441
This should also close https://github.com/docsifyjs/docsify/issues/767

**Summary**

This PR prevents `{docsify-ignore}` and `{docsify-ignore-all}` to be rendered inside other markdown engines like on Github.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Repo settings
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [x] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Tests**

```
$ mocha ./test/**/*.test.js


  router/history/base
    ✓ toURL without relative path
    relativePath true
      ✓ toURL
      ✓ toURL with double dot
      ✓ toURL child path
      ✓ toURL absolute path

  Docsify public API
    ✓ global APIs are available (183ms)
    Docsify config function
      ✓ allows $docsify to be a function (201ms)
      ✓ provides the hooks and vm API to plugins

  render
    ✓ important content (tips)
    lists
      ✓ as unordered task list
      ✓ as ordered task list
      ✓ normal unordered
      ✓ unordered with custom start
      ✓ nested
    image
      ✓ regular
      ✓ class
      ✓ id
      ✓ no-zoom
      size
        ✓ width and height
        ✓ width
    heading
      ✓ h1
      ✓ h2
      ✓ h3
      ✓ h4
      ✓ h5
      ✓ h6
    link
      ✓ regular
      ✓ linkrel
      ✓ disabled
      ✓ target
      ✓ class
      ✓ id

  router/util
    ✓ resolvePath
    ✓ resolvePath with dot
    ✓ resolvePath with two dots


  35 passing (1s)
```

### CODE REVIEW

**Comment by equinusocio** [comment]
> LGTM.
> 
> Should we be compatible with previous versions? @anikethsaha

If we want to solve #767, i think should not be compatible.

**Comment by Koooooo-7** [comment]
I think it should be backward compatibility.  we'd better keep current congratulation and allowed the new one.
If users haven't used the specific version of docsify, it would cause potential troubles for them. we should make it deprecated, not just remove it directly rn.

**Comment by equinusocio** [comment]
> If users haven't used the specific version of docsify, it would cause potential troubles for them. we should make it deprecated, not just remove it directly rn.

This is how dependencies work. If you don't specify a version you will get the last version, including any `major` releases that always include **breaking changes**. Users should know how how to use it.

**Comment by equinusocio** [comment]
Done

**Pull request merged**
