### PR TITLE
Test suite changes

### PR DESCRIPTION
**Pull request by mohammedsahl**
**Summary**
This PR aims to duplicate the current sidebar e2e tests for the desktop over to mobile. In addition there is a small test for #1243 

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [X] Other, please describe:

Integration tests added. Complete overhaul of `cypress/snapshots/sidebar` snapshots.

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

**The PR fulfills these requirements:**
You have tested in the following browsers: (Providing a detailed version will be better.)

- [X] Electron 78 (headless)

**Other information:**    
Adding `describe` or `context` or `it` changes the filename of the snapshot. This causes test to fail.
In order to use `describe` and `context`, I had to delete all existing snapshots and re-run `npm run test:e2e`.

I verified if the new snapshots generated were correct through manual inspection. In addition I carried out a second verification by running `npm run test:e2e` twice in a row, ensuring all tests pass. 

I expect some of the e2e tests checks to fail for this PR

---

### CODE REVIEW

**Comment by mohammedsahl** [comment]
> One question , did you move the tests to mobile cases or keeping both ?

Keeping both. I simply copied the same tests (with a few minor changes) over to mobile. Mobile is the equvalient of adding 
```JS
cy.viewport('iphone-x`)
cy.visit('localhost:3000`)
```
to `beforeEach`

**Comment by anikethsaha** [comment]
I am seeing some removal of code from the old tests. Can you give me some details about that  ?

thanks

**Comment by mohammedsahl** [comment]
> I am seeing some removal of code from the old tests. Can you give me some details about that ?
> 
> thanks

Sure, no worries! Its mainly because I've wrapped the entire test in a `describe` code block. I was thinking it makes it easier to organize tests that would be added in the future. If you notice, The code that is removed is exactly the same as what was added. 

For example:
[This](https://github.com/docsifyjs/docsify/pull/1254/files#diff-e212933b549ef2e094e04ca2e026e872R7-R26) was removed and [this](https://github.com/docsifyjs/docsify/pull/1254/files#diff-e212933b549ef2e094e04ca2e026e872L6-L24) was added
**Note** you will need to click on "Load diff" to look at the code since the diff is pretty large

**Comment by trusktr** [comment]
It's not as big a deal for test code, but I would prefer to avoid duplicate code if possible, having both mobile and desktop tests import from a shared file.

**Comment by mohammedsahl** [comment]
Gonna close this PR for now. I'll have a look again once again in the near future (~1 week)

**Comment by trusktr** [comment]
@mohammedsahl Another thing you can do instead of closing is leaving it open but mark it as a "draft" PR in the right sidebar. Looks like this:

Screenshot from 2020-07-10 20-48-47


Sorry for lag on my end, It's tax time and have been working on business stuff related to that.

**Pull request closed without merging**
