### PR TITLE
Added npm run dev command

### PR DESCRIPTION
**Pull request by kirbygit**
**Summary**
Added npm run dev command

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
issue #1203 

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Comment by kirbygit** [comment]
I think we should merge the PR from @trusktr so I can make the changes on the README

**Comment by anikethsaha** [comment]
@kirbygit which PR is it ?

**Comment by ianjennings** [comment]
Depends on this PR https://github.com/docsifyjs/docsify/pull/1203

**Comment by anikethsaha** [comment]
Thanks , I guess that is still in WIP

cc @trusktr

**Comment by jhildenbiddle** [comment]
This change doesn't make sense. Running `npm run dev` will start a server which will prevent users from entering the other commands as instructed. This is why the `dev` task is discussed separately.

I agree out our `CONTRIBUTING.md` doc needs some TLC, but this doesn't add value. Closing for now to reduce PR noise.

**Pull request closed without merging**
