### PR TITLE
name option supports automatic update of different paths，like "nameLink".

### PR DESCRIPTION
**Pull request by coolkit-carl**
**Summary**

name option supports automatic update of different paths，like "nameLink".

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [x] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [x] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**I created a multi-language file directory, but the title of the document will never change, so I refer to the "nameLink" update method, so that the name parameter supports {"x": "x"} Object type.

I checked it, it was not much modified, and it worked very stable.**

**Other information:**

---

* [x] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by anikethsaha** [comment]
it looks like you forgot to fill the PR template and Please give details about the PR

**Comment by coolkit-carl** [comment]
> it looks like you forgot to fill the PR template and Please give details about the PR

ok, I updated the description

**Comment by anikethsaha** [comment]
I am still confused with this PR as whats the need ? can you send some before/after images and also the ,motivation behinf this ?

**Comment by coolkit-carl** [comment]
> I am still confused with this PR as whats the need ? can you send some before/after images and also the ,motivation behinf this ?

I need to change the document title automatically when switching between different languages, instead of always using the title of one language, as shown in the figure:

D3102919-51DA-46dd-B90F-D88D2BA929D3
151EF2B2-67A3-4934-8771-379C7621DE14

**Pull request closed without merging**
