### PR TITLE
fix: Fix font-size changing for code in headings

### PR DESCRIPTION
**Pull request by Yash-Singh1**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Repo settings
- [ ] Other, please describe:

If changing the UI of the default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

### CODE REVIEW

**Comment by Yash-Singh1** [comment]
Before:
Screenshot from 2020-12-27 16-11-26
After:
Screenshot from 2020-12-27 16-11-39

**Comment by trusktr** [comment]
This bugged me before too, and I put custom style on my site.

@jhildenbiddle should this sort of change be saved for v5? It is an ideal change, but does have some chance (even if small) to break someone's v4 site.

**Comment by anikethsaha** [comment]
I agree, it may break snapshot testing as far as I can think. 
But I think its worth adding now as we really dont know how long it will take to land v5. 
This looks more like a bug so I guess we can add this.

let me know if I am missing anything

**Review by anikethsaha — APPROVED** [review]

**Comment by sy-records** [comment]
I think it can be released from v4.12.0

**Review by jhildenbiddle — APPROVED** [review]
LGTM

**Pull request merged**
