### PR TITLE
[Docs] Update cover.md

### PR DESCRIPTION
**Pull request by sy-records**
**Summary**

for #1132
Support multiple covers, more than one, right?
If yes, you can also merge docsifyjs/docs-zh#18、docsifyjs/docs-es#2、docsifyjs/docs-ru#6、docsifyjs/docs-de#1

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

---

* [ ] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by anikethsaha** [comment]
also, You can merge those other repos PR, I have invited you to translator team

**Comment by sy-records** [comment]
ok.

**Comment by sy-records** [comment]
@anikethsaha docsifyjs/docs-zh#18 no permission to write.

**Comment by anikethsaha** [comment]
try again

**Comment by sy-records** [comment]
OK, thank you.

**Pull request merged**
