### PR TITLE
fix: Cannot read property 'classList' of null

### PR DESCRIPTION
**Pull request by sy-records**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

fix https://github.com/docsifyjs/docsify/issues/1526

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Repo settings
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

### CODE REVIEW

**Review by Koooooo-7 — DISMISSED** [review]
LGTM.

**Comment by trusktr** [comment]
Why does this error happen? It could indicate some other issue.

Different topic: I think the issue template is fairly useless. Most PRs lately have no description (which isn't good), and the rest of the template is usually just noise.

**Review by trusktr — APPROVED** [review]

**Comment by sy-records** [comment]
> Why does this error happen? It could indicate some other issue.

The problem exists under IE11, I'm not quite sure of the exact cause

> Different topic: I think the issue template is fairly useless. Most PRs lately have no description (which isn't good), and the rest of the template is usually just noise.

Yes, many do not follow the issue template to ask questions.

**Comment by sy-records** [comment]
image

I have reproduced the problem.

without setting `name`.
Set `hideOtherSidebarContent` in search.

```diff
- name: 'docsify',
  search: {
+    hideOtherSidebarContent: true,
  },

```

**Review by jhildenbiddle — APPROVED** [review]

**Review by Koooooo-7 — APPROVED** [review]

**Pull request merged**
