### PR TITLE
upgrade marked

### PR DESCRIPTION
**Pull request by awm086**
**Summary**
- upgrade marked to 0.7.0 to fix package vulnerability  

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [X] Other, please describe: Update package 

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

You have tested in the following browsers: (Providing a detailed version will be better.)

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Comment by anikethsaha** [comment]
Thanks for the PR 👍 

Could you rebase? and I need to check if there is any breaking changes in this updating from `marked` side or not. and we will merge this soon 👍

**Comment by vvni** [comment]
I want to know when marked is updated？

**Comment by anikethsaha** [comment]
here https://github.com/docsifyjs/docsify/pull/934/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R45

But docsify is not released since then. Will do the release soon

**Comment by vvni** [comment]
👌Thanks！

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=10.0.32&pv=10.15.1&source=email_footer_2]
On Tue, Nov 26, 2019 at 4:36 PM, Anix <notifications@github.com> wrote:
here https://github.com/docsifyjs/docsify/pull/934/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R45 [https://github.com/docsifyjs/docsify/pull/934/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R45]

But docsify is not released since then. Will do the release soon

**Comment by anikethsaha** [comment]
I guess we can close this 👍

**Pull request closed without merging**
