### PR TITLE
fix: search does not find the contents of the table

### PR DESCRIPTION
**Pull request by sy-records**
**Summary**
The previous commit #1015 only fixed the situation where there was no content before the table. like this:

```
## Errno List

| C Name  | Value | Description       |
| ------- | ----- | ----------------- |
| Success | 0     | Success           |
| EPERM   | 1     | Operation not per |
```
image

But this one below is not searchable.
```
## Errno List

Here are some descriptions....

| C Name  | Value | Description       |
| ------- | ----- | ----------------- |
| Success | 0     | Success           |
| EPERM   | 1     | Operation not per |
```
image

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

---

* [ ] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by sy-records** [comment]
Is now okay? @anikethsaha

**Comment by anikethsaha** [comment]
remove the scope, `search` , currenlty we dont have scope. 

Also, change the commit message as well.

**Comment by Koooooo-7** [comment]
and I prefer to use `return` in some cases direcly to avoid useing more `if else` branch.
Idk whether it should be applied to docsify.
WDYT ?

**Comment by sy-records** [comment]
@Koooooo-7 Is there a problem with using `return` in `forEach`?

https://github.com/docsifyjs/docsify/blob/d0ecc423da45cc810bf490d7494c5493df48ca9f/src/plugins/search/search.js#L79-L112

**Comment by anikethsaha** [comment]
is there any issue which is being fixed by this PR ? feel free to close that one

**Comment by sy-records** [comment]
No relevant issue. I found the problem, fixed it by the way.

**Comment by anikethsaha** [comment]
great

**Pull request merged**
