### PR TITLE
history router mode search result fix

### PR DESCRIPTION
**Pull request by artisan-yu**
## **Summary**

in History mode, search results should not link to hash routes, but to regular routes.

## **For any code change,**

- [ ] Related documentation has been updated if needed
- [x] Related tests have been updated or tests have been added

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

## **Tested in the following browsers:**

- [x] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Comment by jhildenbiddle** [comment]
@ayu-666 --

Please provide a more detailed description of the issue being fixed, steps to reproduce, screenshots (if appropriate), etc. Without more information, PRs can not be tested and approved. Thanks!

**Comment by trusktr** [comment]
Based on the change, this makes search results **not** use `#` in front of URLs for search results, because in History mode we do not want to navigate to hashes.

@ayu-666 can you please add a test for this?

**Comment by ayu-666** [comment]
image
when using the history mode, navigate to hash link will cause 404

**Comment by jhildenbiddle** [comment]
@ayu-666 -- There is also a minor ESLint error (see checks above, click [here](https://github.com/docsifyjs/docsify/runs/5131739929?check_suite_focus=true) for details). You can most likely fix this by running `npm run lint:fix`.

Thanks!

**Review by jhildenbiddle — CHANGES_REQUESTED** [review]
Please fix ESLint errors and add an integration test. Thanks!

**Pull request closed without merging**
