### PR TITLE
fix: search cannot search list content

### PR DESCRIPTION
**Pull request by sy-records**
**Summary**

fix: search cannot search list content

```
# Test

balabala...

* this is content
* this is content
```

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Repo settings
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

### CODE REVIEW

**Review by anikethsaha — APPROVED** [review]
LGTM 

As the infra for plugin testing is not set up yet, I think we can merge this. Though if you can setup or add tests for this, it would be great.

**Comment by sy-records** [comment]
> As the infra for plugin testing is not set up yet, I think we can merge this. Though if you can setup or add tests for this, it would be great.

I also want to add tests, but I don't know how to write them...

**Review by Koooooo-7 — APPROVED** [review]

**Comment by Koooooo-7** [comment]
...I m working on the test rn. 😅

**Comment by sy-records** [comment]
Well, then you can resubmit the PR for changes if you have questions.

**Pull request merged**
