### PR TITLE
doc: fix broken link

### PR DESCRIPTION
**Pull request by revolunet**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

---

* [ ] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by anikethsaha** [comment]
Thanks a lot for your PR 👍 

Actually in `/awesome` page, we are remotely rendering the `readme` of `awesome-docsify` repo. So the content is basically the same. and it won't redirect to that repo and it will stay in our docs site only. So I think the current one is better as we don't want users to redirect to Github and then again have to come back . 

Closing this.
Let me know if you want to add something to it 👍

**Comment by revolunet** [comment]
Hi, fine but this link returns a 403 for me

**Comment by revolunet** [comment]
404

**Comment by anikethsaha** [comment]
working fine for me 

https://docsify.js.org/#/awesome?id=plugins

is this the link you are talking about ?

**Comment by revolunet** [comment]
Its when i click "awesome docsify" in the sidebar

**Comment by anikethsaha** [comment]
image

working for me
Am I missing something ?

**Comment by revolunet** [comment]
This is here and there's no hash in the link for me 

Capture d’écran 2020-04-03 à 17 05 39

Capture d’écran 2020-04-03 à 17 04 57

**Comment by anikethsaha** [comment]
you are using the wrong link . 
use `https://docsify.js.org/#/awesome`. 
our docs link is `https://docsify.js.org`
and the development branch preview is at `https://docsifyjs.netlify.com/`

**Comment by revolunet** [comment]
ho, ok my bad. i dont remember where i got this one !

thanks for this great tool 💛

**Pull request closed without merging**
