### PR TITLE
test: for making test steady in docker locally.

### PR DESCRIPTION
**Pull request by Koooooo-7**
## **Summary**
For test locally, add docker options.

## **What kind of change does this PR introduce?**

Test

## **For any code change,**

- [ ] Related documentation has been updated if needed
- [ ] Related tests have been updated or tests have been added

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

## **Tested in the following browsers:**

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Comment by trusktr** [comment]
Looks good. This doesn't affect anything else, and allows people an alternative way to run tests locally. Let's merge it.

**Comment by trusktr** [comment]
All checks passed after a re-run. Let's fix those pesky flaky tests.

**Review by trusktr — APPROVED** [review]

**Comment by trusktr** [comment]
As these added package.json scripts are harmless and do not affect any other processes, I will merge. I've been unable to run tests locally for way too long.

**Comment by sy-records** [comment]
This should be merged with squash

**Pull request merged**
