### PR TITLE
fix search focus color to theme primary color

### PR DESCRIPTION
**Pull request by BoomProj**
## **Summary**

Fix search focus color to theme primary color

## **For any code change,**

- [ ] Related documentation has been updated if needed
- [ ] Related tests have been updated or tests have been added

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

## **Tested in the following browsers:**

- [x] Chrome
- [x] Edge

### CODE REVIEW

**Review by trusktr — CHANGES_REQUESTED** [review]
Hello, thanks for the idea. The plug-in still needs to own the style. Plugins can reuse CSS variables.

Can you do this without removing the CSS from the plugin?

**Comment by BoomProj** [comment]
I found another way.  Set themeColor in the index.html,but this configuration doesn't create by  default.

**Review by sy-records — CHANGES_REQUESTED** [review]
please remove `docs/_images/vuiot-dark.png`

**Comment by jhildenbiddle** [comment]
@BoomProj --

It is unclear what issue this PR is designed to fix. The search plugin honors Docsify's [themeColor](https://docsify.js.org/#/configuration?id=themecolor) option as expected.

Docsify "Vue" theme w/ default theme color:

CleanShot 2022-03-07 at 14 45 35@2x

Docsify "Vue" theme with `themeColor` set to `red:

CleanShot 2022-03-07 at 14 46 06@2x

Closing this PR for now. If you believe an issue still exists, feel free to create an issue or request that this PR be re-opened after changes have been made.

Thanks!

**Pull request closed without merging**
