### PR TITLE
fix: upgrade dompurify from 2.2.2 to 2.2.6

### PR DESCRIPTION
**Pull request by sy-records**
Replace #1470

### CODE REVIEW

**Review by Koooooo-7 — COMMENTED** [review]
it seems there has the `security/snyk` issue on CI.
@anikethsaha  could u plz check and fix it  intead of manual upgrade？

**Comment by anikethsaha** [comment]
Not sure whether I get this correctly but you are asking for a PR from snyk ? @Koooooo-7

**Comment by Koooooo-7** [comment]
> Not sure whether I get this correctly but you are asking for a PR from snyk ? @Koooooo-7

yup, the PR of snyk always deletes the dependencies about `vue` in `package-lock.json`. f.e see #1470 .

**Comment by Koooooo-7** [comment]
I guess we need move the `vue` from `devDependencies` to `dependencies` .

**Comment by sy-records** [comment]
The reason I closed #1470 was because it was out of date, two versions short

**Comment by sy-records** [comment]
Maybe snyk doesn't recognize this style

https://github.com/docsifyjs/docsify/blob/develop/package.json#L106-L107

**Comment by jhildenbiddle** [comment]
> Maybe snyk doesn't recognize this style
> 
> https://github.com/docsifyjs/docsify/blob/develop/package.json#L106-L107

@sy-records -- Let's ping Snyk and let them know that their system appears unable to determine when two versions of the same library are listed as dependencies. Otherwise we're just going to run into this issue over and over again. Sounds like @anikethsaha maintains our account?

**Comment by anikethsaha** [comment]
> > Maybe snyk doesn't recognize this style
> > https://github.com/docsifyjs/docsify/blob/develop/package.json#L106-L107
> 
> @sy-records -- Let's ping Snyk and let them know that their system appears unable to determine when two versions of the same library are listed as dependencies. Otherwise we're just going to run into this issue over and over again. Sounds like @anikethsaha maintains our account?

I think @sy-records does have the access, right ?
if not please tell me how to give access, I tried but it wasnt successfull.

**Comment by sy-records** [comment]
I private messaged you in discord @anikethsaha

**Pull request merged**
