### PR TITLE
Fix: Theme preview in Mobile Chrome, Safari

### PR DESCRIPTION
**Pull request by iNuanfeng**
## **Summary**

I fix the sidebar style in mobile, when the body height is too small.

| before | after |
| ------ | :---- |
| IMG_5942 |IMG_5943 2 |

## **What kind of change does this PR introduce?**

Bugfix

## **For any code change,**

- [ ] Related documentation has been updated if needed
- [ ] Related tests have been updated or tests have been added

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

## **Tested in the following browsers:**

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Comment by sy-records** [comment]
Can you provide a reproducible environment or repo?

**Comment by Koooooo-7** [comment]
Concurred with @sy-records .

**Comment by trusktr** [comment]
@sy-records @Koooooo-7 the repo is linked at the top (https://github.com/iNuanfeng/docsify), and the vercel bot provided the live demo.

I tested it (deleted a bunch of elements in devtools inspector) but was not able to reproduce:

Capture

But I didn't try on an iPhone. Anyone else with an iPhone?

**Comment by sy-records** [comment]
It's normal for me to use iPhone to view.

image

**Comment by iNuanfeng** [comment]
> @sy-records @Koooooo-7 the repo is linked at the top (https://github.com/iNuanfeng/docsify), and the vercel bot provided the live demo.
> 
> I tested it (deleted a bunch of elements in devtools inspector) but was not able to reproduce:
> 
> Capture
> 
> But I didn't try on an iPhone. Anyone else with an iPhone?

He will reappear on the iPhone.
My IOS version is 13.4.1
The chrome version on my iPhone is 87.0.4280.163

**Comment by iNuanfeng** [comment]
> It's normal for me to use iPhone to view.
> 
> image

When the content of the document is small, it will be reproduced

**Comment by iNuanfeng** [comment]
@sy-records When the content of the document is too small, it will be reproduced

**Comment by iNuanfeng** [comment]
你好，我的MR（https://github.com/docsifyjs/docsify/pull/1683）中，指的是文档内容过少，没有撑满一屏长度的时候，左侧侧边栏会无法显示全。环境是iphone下的chrome



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月6日(星期一) 下午5:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [docsifyjs/docsify] Fix: Theme preview in Mobile Chrome, Safari (PR #1683)





 
It's normal for me to use iPhone to view.
 

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sy-records** [comment]
I don't have that version of the device.

I am using IOS15 and Chrome 97 is working fine.

https://github.com/iNuanfeng/iNuanfeng.github.io

**Comment by trusktr** [comment]
@sy-records did you try with a small amount of content? Your screen shows a lot of content beyond the end of the bottom of the screen. See our screenshots that have little content.

**Comment by sy-records** [comment]
Yes, I tested it with his repo.

**Comment by trusktr** [comment]
@sy-record but in your screenshot, I see full content. Can you post a screenshot with small (not tall) content?

> It's normal for me to use iPhone to view.
> 
> image

**Comment by sy-records** [comment]
image

**Comment by iNuanfeng** [comment]
@sy-records So, It may be a browser compatibility

**Comment by trusktr** [comment]
Hmm, yeah, just can't reproduce it yet.

But, if this fixes your issue, I think it is safe to merge because our snapshot tests are passing.

Wdyt @Koooooo-7 @sy-records ?

**Review by sy-records — APPROVED** [review]

**Review by trusktr — APPROVED** [review]

**Comment by iNuanfeng** [comment]
@trusktr @sy-records @Koooooo-7 Thank you !

**Comment by trusktr** [comment]
@iNuanfeng no prob!

@Koooooo-7 @sy-records we should add iPhone/Android tests. I learned how to configure playwright for that yesterday. WIP..

**Pull request merged**
