### PR TITLE
update readme, add Discord to site, other improvements/changes

### PR DESCRIPTION
**Pull request by trusktr**
**Summary**

- Clean up README
- update badges (looks better if they aren't too many at the top and not mixed rounded and square borders), added a Discord badge
- Replace Gitter links with Discord links.

Preview here:  https://github.com/docsifyjs/docsify/tree/update-readme

**TODO:**

- [ ] add Discord badge or widget in the docsify site
- [ ] simplify README: link to the site and docs rather than having small bits of information in the README that are duplicated on the website.
- [ ] If we care about the donate/sponsor stuff, then we should make it look better, or else remove it
- [ ] If we keep sponsor stuff, let's remove the sponsor badges from the top. The links will be completely obvious in the backers/sponsors section once we clean up the length of the README.
- [ ] If we keep sponsor stuff, let's decide how it will work. At the moment it links to different places, one place is opencollective (not under Docsify's own account) and the other place is QingWei-Li's personal donation page on his GitHub account, which has further links to other places. I think we should clean this up.
- [ ] autogenerate the contributors list (if not already?)

**inspiration**

As a source of inspiration, I'm looking at AssemblyScript's [README](https://github.com/AssemblyScript/assemblyscript/blob/master/README.md) (and others):

- It is simple and contains minimal info with links to the website
- The website contains the details
- The top of the README does not contain sponsor/donation info, but rather focuses on what the library is. We should do this too.
- Anything that is duplicated on website and README (namely sponsor stuff) is taken from the site and re-used in the README to avoid duplication of effort.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [x] Related documents have been updated
- [ ] Related tests have been updated

### CODE REVIEW

**Comment by anikethsaha** [comment]
> [ ] simplify README: link to the site and docs rather than having small bits of information in the README that are duplicated on the website.

Agreed. I guess we can move the contributing section to a `CONTRIBUTING.ms` 


> [ ] If we care about the donate/sponsor stuff, then we should make it look better, or else remove it

I dont think we should remove it . Lets keep those. Remove the similar project table. and move the sponsor's thing to top. like [they](https://github.com/AssemblyScript/assemblyscript) did

> * If we keep sponsor stuff, let's remove the sponsor badges from the top. The links will be completely obvious in the backers/sponsors section once we clean up the length of the README.

yeah, move the sponsor's list to top

> * If we keep sponsor stuff, let's decide how it will work. At the moment it links to different places, one place is opencollective (not under Docsify's own account) and the other place is QingWei-Li's personal donation page on his GitHub account, which has further links to other places. I think we should clean this up.

the opencollective is docsify  's own account. We need to keep that. Also contributor's list is being auto-generated by the opencollective's link as well. SO we can keep those like a current. 

>  QingWei-Li's personal donation page on his GitHub account

lets keep this. He has set up a GitHub repo for that. I guess we can add open collective badge as well.

**Comment by anikethsaha** [comment]
Also, I guess we can add a discord icon in the navbar 

like this. 

image

**Comment by trusktr** [comment]
Updated the TODO list at the top, with "Fix broken Contributing page: https://docsify.js.org/#/contributing. It is linked to here: https://docsify.js.org/#/awesome?id=contributing"

**Comment by kirbygit** [comment]
Will do this after I figure out the lighthouse issue

**Comment by trusktr** [comment]
> I dont think we should remove it . Lets keep those. Remove the similar project table. and move the sponsor's thing to top. like they did

Based on the chat on Discord #maintainers, I think we can remove it until when/if we add new links to funding that current maintainers can manage. (cc @jhildenbiddle)

**Comment by trusktr** [comment]
> yeah, move the sponsor's list to top

I think we should have brief information about the project at the top, linking to the website for more info, then sponsors after right below it, and nothing more to keep it simple.

> contributor's list is being auto-generated by the opencollective's link as well. SO we can keep those like a current.


Does that include code contributors? Or only OpenCollective contributors?

**Comment by anikethsaha** [comment]
> > I dont think we should remove it . Lets keep those. Remove the similar project table. and move the sponsor's thing to top. like they did
> 
> Based on the chat on Discord #maintainers, I think we can remove it until when/if we add new links to funding that current maintainers can manage. (cc @jhildenbiddle)

lets have some thoughts in discord. I messaged already

**Comment by anikethsaha** [comment]
> Does that include code contributors? Or only OpenCollective contributors?

both

**Comment by trusktr** [comment]
I'm new to opencollective. So yeah, if it generates the contributor list
based on the commits from the GitHub repo, then that's great.

#!/JoePea

**Comment by kirbygit** [comment]
Made a PR for this at #1274 

In regards to the link on the donating, does the link redirects to the old maintainer?

**Comment by anikethsaha** [comment]
Any update here ?

**Comment by jhildenbiddle** [comment]
@anikethsaha @sy-records @Koooooo-7 

This PR is woefully outdated, contains relatively minor changes (shuffling icons on `README.md` and swapping Gitter links to Discord), and contains changes that should really be split into separate PRs. I also think our `README.md` should prioritize end-users first (more attention to https://docsify.js.org/, description of the project, screenshots, etc.) instead of the dev/backer/contributions focus it has now (all of which we can debate separately)

My suggestion is to close this PR as well as #1274, then create new PRs for the following:

1. Replace Gitter with Discord (multiple files throughout project)
2. Improve first-time reading experience of `README.md` (suggested priority: 1. users, 2. devs, 3. backers)
3. Update `CONTRIBUTING.md` for better dev onboarding

**Review by Koooooo-7 — COMMENTED** [review]
I updated some docs, will u wanna continue finish this 😃.

**Pull request closed without merging**
