### PR TITLE
Eslint fixes for v4x

### PR DESCRIPTION
**Pull request by giulioambrogi**
**Summary**
Fix https://github.com/docsifyjs/docsify/issues/987

**Fulfilled requirements**

- [X] Npm script fix
- [X] .eslintrc updated as per requirements
- [X] Lint Errors fix
- [X] Lint Warning fix
- [X] Add the linting to travis

**Other information:**
I've added `"mocha": true` to the `env` object in `.eslintsrc` to cover the tests. And removed  the hard-coded `/* eslint-env node, chai, mocha */` I've found in a couple of spec files.

### CODE REVIEW

**Comment by anikethsaha** [comment]
Thanks for the PR.

> I've added "mocha": true to the env object in .eslintsrc to cover the tests. And removed the hard-coded /* eslint-env node, chai, mocha */ I've found in a couple of spec files.

We will migrate to `jest` so you can make it `jest`

**Comment by anikethsaha** [comment]
Cool,
I will review it locally against my e2e testing branch to see if anything is breaking or not.

**Comment by giulioambrogi** [comment]
> some changes with if conditions regarding null and undefined.

Re the `null`/`undefined` changes I was looking for some unit tests to cover that but couldn't find any.
I'm very new to the repo so I don't know whether this is on purpose or not, e.g. you prefer having more integration tests than unit tests. Any idea?

**Comment by anikethsaha** [comment]
We don't have any tests as of now. 
I am working on e2e tests here #986 
we need to increase test coverage in order to get the confidence of merging PRs.

**Comment by anikethsaha** [comment]
@giulioambrogi could you resolve the conflicts

**Comment by giulioambrogi** [comment]
> @giulioambrogi could you resolve the conflicts

Done

**Comment by anikethsaha** [comment]
> > @giulioambrogi could you resolve the conflicts
> 
> Done

Cool 👍

**Pull request merged**
