### PR TITLE
[Feature Enhancement] Improved Emoji Support

### PR DESCRIPTION
**Pull request by felangel**
**Summary**

The existing emoji plugin is lacking support for lots of emojis. I have modified the emoji plugin to source emoji data from https://raw.githubusercontent.com/liguoqinjim/github_emoji/master/github_all/README.md instead.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge
- [X] IE

If adding a **new feature**, the PR's description includes:

- [X] A convincing reason for adding this feature
- [x] Related documents have been updated
- [x] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

---

* [x] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by felangel** [comment]
@timaschew @jingsam can you take a look?

**Comment by jingsam** [comment]
@felangel thanks for your PR. The PR looks for good for me. It would be better if you just extend `allGithubEmoijs` varibables, not totally rewrite the whole file.

**Comment by felangel** [comment]
@jingsam can you give an example of how you'd like me to structure it?

**Comment by jingsam** [comment]
Just add missing emoijs in 

```
const AllGithubEmoji = [
  ...
]
```

**Comment by felangel** [comment]
`AllGithubEmoji` was just an array of emoji id strings and the way they were being resolved was directly via the emojis endpoint.

The approach in the PR is to use the `unicode` endpoint and be able to just update the mapping of emoji id to image url. I'm not sure what you mean by just add the missing emojis since the whole data structure is different.

**Comment by jingsam** [comment]
I thought it would be better just use Github Emoji API https://api.github.com/emojis

**Comment by felangel** [comment]
@jingsam sounds good. I've updated the PR 👍

**Comment by jingsam** [comment]
LGTM @felangel thanks for your PR. Ops, it seems that I don't have the permission to merge this PR. @jthegedus How do you think about it?

**Comment by timaschew** [comment]
We had an discussion about emojis here: https://github.com/docsifyjs/docsify/issues/779

@felangel please verify if this PR is aligned with the final agreement in #779

**Comment by felangel** [comment]
@timaschew i believe it aligns with #779 because I just added missing emoji names and left the lookup as is. It’s still using https://api.github.com/emojis to map the emoji name to the unicode url. 👍

**Comment by anikethsaha** [comment]
+1 for this

**Comment by felangel** [comment]
@anikethsaha if you're okay with the changes, I think we can merge this

**Comment by anikethsaha** [comment]
I think we should wait for couple of days and we can merge this.

cc @timaschew @jingsam /

**Comment by timaschew** [comment]
I've revisited this PR and #779.  
This PR is basically just a one time fix. But let's merge ;)

**Pull request merged**
