### PR TITLE
docs: update formatUpdated

### PR DESCRIPTION
**Pull request by Koooooo-7**
## **Summary**
Add the config `formatUpdated: '{YYYY}/{MM}/{DD} {HH}:{mm}'` in docs to make this plugin more clearly.

## **What kind of change does this PR introduce?**

Docs 

## **For any code change,**

- [x] Related documentation has been updated if needed
- [ ] Related tests have been updated or tests have been added

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

## **Tested in the following browsers:**

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Comment by trusktr** [comment]
It doesn't appear to work, if you check on the bottom of any page in the preview, you will see this:

Screenshot from 2021-10-04 12-24-38

**Comment by Koooooo-7** [comment]
@trusktr 
yea, I also checked the preview. but it works well locally. It seems some other issues here.

**Review by sy-records — CHANGES_REQUESTED** [review]
Documents can add `formatUpdated`, but it is not necessary to add `Last modified` to `index.html`.

Because we use GitHub Pages, there are problems, see #1157

**Comment by Koooooo-7** [comment]
@sy-records  cool, I remove the code changes. and I will take a look on how to make it works as well.

**Review by sy-records — APPROVED** [review]

**Pull request merged**
