### PR TITLE
fix sidebar closing problem on mobile while clicking among catalog items

### PR DESCRIPTION
**Pull request by bigablecat**
## **For any code change,**

- [x] Related documentation has been updated if needed
- [ ] Related tests have been updated or tests have been added

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

## **Tested in the following browsers:**

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [ ] IE

### CODE REVIEW

**Comment by bigablecat** [comment]
details description of problem:
Under mobile mode, while choosing from catalog items, any click on the catalog will causing the sidebar closing. 
A resonable design should be clicking on the content part other than any part of the body to trigger the sidebar closing.

**Comment by sy-records** [comment]
Can you add tests to it?

**Comment by bigablecat** [comment]
> Can you add tests to it?

I'd like to add tests. 
Where could I find instructions about what kind of tests and how could I add tests?

**Comment by jhildenbiddle** [comment]
This change solves one problem (for some) while introducing a new problem (for everyone): the sidebar menu no longer auto-closes when new content is loaded. This means *all* users will be forced to manually close the sidebar after navigating to a new page. While some may prefer this behavior, it is not safe to assume everyone will.

The correct way to address this issue is by adding support for expand/collapse toggles in the sidebar that exist only to hide/show content. Docsify does not support this today, but there are relative easy ways to implement it. 

For example:

```markdown
* Text Heading (no expand/collapse)
  * [Page 1](page1.md)
  * [Page 2](page2.md)

+ Toggle Heading (click to expand)
  + [Page 1](page1.md)
  + [Page 2](page2.md)

- Toggle Heading (click to collapse)
  - [Page 1](page1.md)
  - [Page 2](page2.md)
```

---

<strong>Text Heading</strong>
<ul>
  <li><a href="#">Page 1</a></li>
  <li><a href="#">Page 2</a></li>
</ul>

<details open>
  <summary>Toggle Heading (click to collapse)</summary>
  <ul>
    <li><a href="#">Page 1</a></li>
    <li><a href="#">Page 2</a></li>
  </ul>
</details>

<details>
  <summary>Toggle Heading (click to expand)</summary>
  <ul>
    <li><a href="#">Page 1</a></li>
    <li><a href="#">Page 2</a></li>
  </ul>
</details>

---

This can all be done by modifying the markdown parser's handling of `<li>` elements and updating the sidebar toggle logic to auto-close the sidebar when the URL changes (not `onClick`).

Recommendation is to create a feature request for expand/collapse toggles in the sidebar menu where the implementation details can be discussed in more details.

**Comment by bigablecat** [comment]
@jhildenbiddle  
that sounds reasonable, thanks for your kind advice

@sy-records 
thanks for your review as well

**Pull request closed without merging**
