### PR TITLE
fix #932 - Add embed gist instructions to Embed Files

### LINKED ISSUE #932: Is this repository no longer managed?
## Feature request
- I translated docsify to KOREAN ( https://github.com/JUNWOO45/docsify-kr )
#### What problem does this feature solve?
- But I dont know how to merge.

#### How should this be implemented in your opinion?
- Plz tell me how.

#### Are you willing to work on this yourself?
- Sure!

### LINKED ISSUE #982: Show Gist In Markdown
## Bug Report

hello,I have a problem. I write gist embed link in markdown,but docsify don't show it.

I want to know how to show gist in docsify

#### Steps to reproduce

- index.html

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <link rel="icon" href="_media/favicon.ico">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="description" content="Description">
  <meta name="viewport"
    content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/vue.css">

  <!-- mermaid -->
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.css">
  <script src="//cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
</head>

<body>
  <div id="app"></div>
  <script>
    mermaid.initialize({ startOnLoad: false });
    window.$docsify = {
      repo: 'haozibi/',
      auto2top: true,
      subMaxLevel: 2,

      executeScript: true,

      loadSidebar: true,
      loadNavbar: true,
      search: 'auto', 
      markdown: {
        renderer: {
          code: function (code, lang) {
            if (lang === "mermaid") {
              return (
                '<div class="mermaid">' + mermaid.render(lang, code) + "</div>"
              );
            }
            return this.origin.code.apply(this, arguments);
          }
        }
      },
    }
  </script>
  <script src="//unpkg.com/docsify/lib/docsify.min.js"></script>

  <script src="//unpkg.com/docsify/lib/plugins/external-script.js"></script>
  <script src="//unpkg.com/docsify/lib/plugins/search.js"></script>
  <script src="//unpkg.com/docsify/lib/plugins/emoji.js"></script>
  <script src="//unpkg.com/docsify/lib/plugins/zoom-image.js"></script>
  <script src="//unpkg.com/docsify-copy-code"></script>

  <script src="//unpkg.com/prismjs/components/prism-go.js"></script>
  <script src="//unpkg.com/prismjs/components/prism-bash.js"></script>
  <script src="//unpkg.com/prismjs/components/prism-python.js"></script>
  <script src="//unpkg.com/prismjs/components/prism-markdown.js"></script>
</body>

</html>
```

- markdown

```markdown
# test

<script src="https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63.js"></script>
```

#### What is current behaviour

Chrome console show

```conosle
Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
```

I am not very good at the FrontEnd, so I am confused about the problem. sorry~~

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: Mac OS 10.13.6
- Node.js version: 
- npm/yarn version: 
- Browser version: 79.0.3945.79（64 Bit）
- Docsify version: 
- Docsify plugins:

### PR DESCRIPTION
**Pull request by MichaelCurrin**
**Summary**

Added gist instructions to Embed Files page. Closes #982.

Also cleaned up the grammar on the first part of the page.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

**Other information:**

---

* [ ] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by MichaelCurrin** [comment]
I'll check the live preview tomorrow - I am having internet issues today.

**Comment by MichaelCurrin** [comment]
Can I request a small demo gist created under docsify account? Then I can have a live example.

One gist with two files such as:

`content.md`
```
This is a **markdown** file in a gist.
```
And 

`script.js`
```
console.log("This is a script in a gist");
```

`README.md`
```
This gist is used an example of embedding gist - see https://docsify.js.org to read the docs.
```

**Comment by anikethsaha** [comment]
@MichaelCurrin here you go https://gist.github.com/anikethsaha/f88893bb563bb7229d6e575db53a8c15

**Comment by MichaelCurrin** [comment]
@anikethsaha Perfect, thanks! I've used your gist and done some other cleanup.

**Pull request merged**
