### PR TITLE
Docs: Add example for markdown front matter

### PR DESCRIPTION
**Pull request by up9cloud**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you are merging your commits to `master` branch.
* [x] Add some descriptions and refer relative issues for you PR.
* [x] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by timaschew** [comment]
Hi @up9cloud can you please explain what you try to solve with this documentation?
Why you've chosen how to render the front matter as a table?

**Comment by timaschew** [comment]
You're using the [yaml-front-matter](https://www.npmjs.com/package/yaml-front-matter) which has a unclean API compared to this library: https://www.npmjs.com/package/front-matter

Also there is already a built-in front matter in docsify, so there is no point in using another one.

**Comment by up9cloud** [comment]
> Hi @up9cloud can you please explain what you try to solve with this documentation?
> Why you've chosen how to render the front matter as a table?

Umm... i just wanna parse the .md files to github style. Github parse the front matter as a table!

**Comment by up9cloud** [comment]
> You're using the [yaml-front-matter](https://www.npmjs.com/package/yaml-front-matter) which has a unclean API compared to this library: https://www.npmjs.com/package/front-matter
> 
> Also there is already a built-in front matter in docsify, so there is no point in using another one.

Yes, i know there is a plugin for front matter.
I doc this showcase because
1. show how to inject remark if you wanna do thing before marked
2. customize my page before marked.

**Comment by up9cloud** [comment]
oops.. i read the source of plugin front matter, i should use hook beforeEach to do this.

Forgot this pr. 😆

**Comment by up9cloud** [comment]
Okay, i added more example for this.

**Comment by up9cloud** [comment]
Btw, i choose [yaml-front-matter](https://www.npmjs.com/package/yaml-front-matter), because it support browser, so i can easily include cdn files.

https://www.npmjs.com/package/front-matter <<< it seems like i need build first.

**Pull request closed without merging**
