### PR TITLE
[Release]: v4.11.4

### PR DESCRIPTION
**Pull request by anikethsaha**
> ## Do Not Merge
***

|Changelog|
|-|
- ...
-

|Blocking|
|-|

- [x] https://github.com/docsifyjs/docsify/pull/1128 
- [X] https://github.com/docsifyjs/docsify/pull/1188
- [x] Dependency `DOMpurify` is not able to bundled with the output. 

image

image

Any rollup expert can tackle this ?

### CODE REVIEW

**Comment by trusktr** [comment]
I saw a green merge button, so I updated the branch rule to apply to master as well. See here: https://github.com/docsifyjs/docsify/settings/branches

And see this for the syntax: https://stackoverflow.com/questions/53135414 (it is the only way to apply a branch rule to multiple branches with names that have nothing in common)

**Comment by anikethsaha** [comment]
cool
Thanks 👍

**Comment by boopathikumar018** [comment]
Hi @anikethsaha,

I didn't see [docsify-darklight-theme](https://docsify-darklight-theme.boopathikumar.me/) merged. Should I need to fix anything.

**Comment by anikethsaha** [comment]
it has been merged and it will be shipped with this release.

**Comment by boopathikumar018** [comment]
> it has been merged and it will be shipped with this release.

Great Thanks !

**Comment by anikethsaha** [comment]
All blockers are fixed. 

Ready to release once CI is green.

**Comment by anikethsaha** [comment]
@trusktr @jhildenbiddle @Koooooo-7 @sy-records we have a new blocker

**Comment by trusktr** [comment]
This is the file: https://www.github.com/docsifyjs/docsify/tree/develop/test%2Funit%2Fdocsify.test.js

`npm test` does a prod build then runs that test. If that test is passing, it means the bundle loads fine, but maybe it fails once we try it do something on the site?

We can use `window.addEventListener('error', ...)` to observe uncaught errors at the top level (f.e. in the test file).

**Comment by trusktr** [comment]
Didn't it work in the preview? And tests passed? Did you perhaps need to run `npm install`? Or does this happen even after install? And if so, then how did the PR pass testing?

**Comment by anikethsaha** [comment]
Thanks for the heads up @trusktr , I actually had 2-3 docsify code opened in my machine, ran `npm install` in one,  ran the build command in other 😄

**Comment by trusktr** [comment]
Hehe. Happens to the best of us. I can't count how many times I've done something like that. ;)

**Pull request merged**
