### PR TITLE
docs: add notes on "hash" vs "history" routing in the config docs

### PR DESCRIPTION
**Pull request by trusktr**
## **Summary**

expand `routerMode` docs.

## **What kind of change does this PR introduce?**

  Docs

## **For any code change,**

- [x] Related documentation has been updated if needed
- [x] Related tests have been updated or tests have been added

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

## **Tested in the following browsers:**

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Comment by Koooooo-7** [comment]
Maybe we could handle this config internally as a default alias config for sidebar and navbar instead of forcing user to config it manually .

**Comment by trusktr** [comment]
@Koooooo-7 I think that may be possible, but I think it might be a breaking change, and would need to be something we plan for a following major.

**Review by Koooooo-7 — APPROVED** [review]
LGTM.

**Comment by trusktr** [comment]
@Koooooo-7 tracking that ^ issue in https://github.com/docsifyjs/docsify/issues/2133

**Pull request merged**
