### PR TITLE
add new theme: neon

### PR DESCRIPTION
**Pull request by blyndusk**
`neon` is a theme based on existing `vue` theme, but with **dark hues** only, to make reading doc **more enjoyable**, **less tiring**, and because **dark themes are life ❤️**

### CODE REVIEW

**Comment by timaschew** [comment]
Thanks for the contribution.

We plan to switch to docsify themeable.
This make all current themes obsolete.

**Comment by blyndusk** [comment]
Got it, is it still possible to integrate it the time the migration is done?

**Comment by timaschew** [comment]
Sure. Can you please add integration to the live preview: https://docsify.js.org/#/themes?id=click-to-preview

**Comment by blyndusk** [comment]
I would like, but like you said, we don't have to push files included in `lib`, so it'll be a broken link I think.

**Comment by timaschew** [comment]
I'm talking about to update this file: https://github.com/docsifyjs/docsify/blob/master/docs/themes.md

It's not related to the lib directory.

**Comment by jhildenbiddle** [comment]
Two issues:

1. This theme uses CSS custom properties which are not supported by browsers that are officially supported by docsify (IE 11 and Edge 12-15). Any theme or plugin listed on official docs should work in all browsers supported by docsify.

   [docsify-themeable](https://jhildenbiddle.github.io/docsify-themeable) also uses CSS custom properties but includes a [ponyfill](https://github.com/jhildenbiddle/css-vars-ponyfill) that allows legacy browsers to handle them. If/when docsify-themeable is integrated into the main repo CSS, docsify will then support CSS custom properties in legacy browsers as well. But if/when this happens, docsify themes should be made up of [docsify-themeable properties](https://jhildenbiddle.github.io/docsify-themeable/#/customization) and not CSS that affects layout.

1. Themes and plugins created by the community should be added to [awesome-docsify](https://github.com/docsifyjs/awesome-docsify), not the the main repo. The only themes and plugins that should be added to the main docsify repo are the ones that the docsify team intends to take ownership of and officially support.

Hope you don't mind me chiming in on this one. My goal is to prevent a PR from being merged or changes being made that will have to be revisited if/when docisfy-themeable is integrated.

**Comment by blyndusk** [comment]
Understood @timaschew , I will do it!

no problem @jhildenbiddle , thank you for your advices, I will make changes in consequence.

**Pull request closed without merging**
