### PR TITLE
update the name for "Simplified Chinese"

### PR DESCRIPTION
**Pull request by awxiaoxian2020**
## **Summary**

The term "简体中文" is a more accurate representation of “Chinese”.
.

## **What kind of change does this PR introduce?**

Docs

## **For any code change,**

- [ ] Related documentation has been updated if needed
- [ ] Related tests have been updated or tests have been added

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

## **Tested in the following browsers:**

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Comment by awxiaoxian2020** [comment]
@sy-records , Could you please have a review for this PR?

**Review by sy-records — DISMISSED** [review]
Thanks, LGTM!

**Comment by awxiaoxian2020** [comment]
I think we can merge this PR.

**Comment by awxiaoxian2020** [comment]
> IIRC,  the `ZH`, which is the `ISO 639–1 language code` for Chinese as "written Chinese". 
> There is no the sort of `Simplified Chinese` or  `Traditional Chinese` thing.

My point is that it's a common expression in opensource project.

**Review by jhildenbiddle — APPROVED** [review]

**Review by sy-records — APPROVED** [review]

**Pull request merged**
