### PR TITLE
docs: add yarn global install docsify-cli

### PR DESCRIPTION
**Pull request by fynntang**

### CODE REVIEW

**Review by sy-records — APPROVED** [review]

**Review by Koooooo-7 — COMMENTED** [review]
Thx for ur input !
IMO, we use the `npm` base to build this project, so we prefer to let end user fellow this way basicly .  
As same as the docs for contributions, such as `npm run dev`.
And I assume that the user who use `yarn` should know how to handle our project.

**Comment by sy-records** [comment]
This is only for installing docsify-cli https://github.com/docsifyjs/docsify-cli#installation

**Comment by fynntang** [comment]
> Thx for ur input !
> IMO, we use the `npm` base to build this project, so we prefer to let end user fellow this way basicly .
> As same as the docs for contributions, such as `npm run dev`.
> And I assume that the user who uses `yarn` should know how to handle our project.

@Koooooo-7  Thanks for the reminder. I'll make it up later

**Comment by Koooooo-7** [comment]
> This is only for installing docsify-cli https://github.com/docsifyjs/docsify-cli#installation

yep, I knew it.
> And I assume that the user who uses yarn should know how to handle our project.

**Comment by trusktr** [comment]
Thanks for the suggestion @fynntang. I don't think this is needed, because `npm` is standard, and if anyone uses an additional tool like `yarn`, `pnpm`, `ied`, etc, then they will know how to use that as an alternative to `npm`.

**Pull request closed without merging**
