### PR TITLE
strip indent when embedding code fragment

### PR DESCRIPTION
**Pull request by Fs02**
**Summary**

This pr fixes wrong indentation when embedding fragment of code.

Code:

image

Before:

image

After:

image

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

---

* [x] DO NOT include files inside `lib` directory.

### CODE REVIEW

**Comment by anikethsaha** [comment]
Thanks for the PR.
Can you please with some indentation based language formatting like for python? Cause changing the indentation affects the code.

**Comment by Fs02** [comment]
Hi, in that case, the current code is already causing some indentation problem for python.
example:
 
image

Before:

image

After:

image

**Note:** I also edited the PR description to provide the original code.

**Comment by Fs02** [comment]
> Thanks. This is much better

Hi @anikethsaha, is there anything I need to do to have this merge? or should I just wait?

Thanks

**Comment by anikethsaha** [comment]
Sorry for the delay

**Comment by Fs02** [comment]
No problem, thank you :)

**Pull request merged**
