### PR TITLE
fix: re-render gitalk when router changed

### PR DESCRIPTION
**Pull request by spiritree**

### CODE REVIEW

**Comment by timaschew** [comment]
Hi @spiritree  
thanks for you contribution.

Can you explain why it's required to render this plugin again?  
Maybe other plugins are affected as well?  
In that case the logic should be extracted into a common helper function or something like that.

@QingWei-Li any feedback?

**Comment by spiritree** [comment]
@timaschew 
The re-render logic is similiar with disqus plugin(https://github.com/docsifyjs/docsify/blob/master/src/plugins/disqus.js).

There is no need to be extracted into a common helper function because it's a unique plugin.

**Comment by timaschew** [comment]
Okay, but why is it required to render it again actually?

**Comment by spiritree** [comment]
@timaschew 
This plugin is a comment component based on Github issue.
So when router changed,you must re-render it to create unique issue.

**Comment by Q-Angelo** [comment]
reference: https://www.nodejs.red/#/tools/docsify

**Pull request merged**
