### PR TITLE
Fix #1101, #704

### LINKED ISSUE #1101: Server Side Rendering appears to no longer work
#### Steps to reproduce
Follow the instructions on Server Side Rendering
https://docsify.js.org/#/ssr

#### What is current behaviour

Following the SSR instructions results in a blank page. 
It looks like the app and config are not being injected by the server.

Using the package.json configuration, I can get `docsify start` to run. 
It looks like there is also a bug in docsify-cli when using the config file `-c` option .

#### What is the expected behaviour

The content should be rendered into the appropriate areas in the HTML template marked by comments.

```
  <!--inject-app-->
  <!--inject-config-->    
```

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: OSX
- Node.js version: v12.13.1
- npm/yarn version: 6.12.1
- Browser version: Latest Chrome and Firefox
- Docsify version: docsify@4.11.3, docsify-cli@4.4.0
- Docsify plugins: None, default install

### PR DESCRIPTION
**Pull request by boxsnake**
**Summary**
When updated, SSR won't work for local docs, throwing an error saying `Cannot call 'indexOf' of undefined`.
This fixed the problem by separate file content fetching. When the path is absolute, rather than fetch the content directly, the manner is separated:
- If the path is an external url, use fetch from `node-fetch`
- If the path is a local file with absolute path, just use `readFileSync` 

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Repo settings
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

### CODE REVIEW

**Comment by boxsnake** [comment]
@anikethsaha I thought I made the wrong way. `isExternal` is not accessible there, thus the file won't be loaded properly.

**Comment by boxsnake** [comment]
> LGTM.
> 
> It does make sense to use `readFileSync` for non external.
> 
> cc @trusktr thoughts ?

@anikethsaha 
Sorry, but I think my work is not finished.
There are many bugs related to the failure for local files.
- The default homepage is not `README.md`
- The file resolve is not from `basePath` config
- The `isExternal` function has some bugs (In Node.js, which work for SSR, there is no `location` object, but the code uses `location` in if clauses)

**Comment by sy-records** [comment]
I also found the problem as you said. Also switching routes will 404 and refreshing will only work.

**Comment by boxsnake** [comment]
> I also found the problem as you said. Also switching routes will 404 and refreshing will only work.

I am still working on fixing it, and will make a fresh PR later.

**Comment by sy-records** [comment]
cool, I suggest you switch a branch to resubmit pr and not make changes directly on `develop`.

**Comment by boxsnake** [comment]
> cool, I suggest you switch a branch to resubmit pr and not make changes directly on `develop`.

I'll make a new PR referring to this one.

**Pull request closed without merging**
