### PR TITLE
add Google verification file to enable URL/indexing inspector

### PR DESCRIPTION
**Pull request by trusktr**
## **Summary**

This file will allow Google to verify we own the site at docsify.js.org. Then we will have access to the indexing tools. Once this is in place, I will figure out how it works, then I will see how to give maintainers access.

The idea is that, with https://github.com/docsifyjs/docsify/pull/1968 enabling history router, we are one step closer to full SEO on Google. By connecting to the Google SEO inspector, I will be able to see how well the site is indexable in history mode, then we'll know what to do next if we need to improve.

## **What kind of change does this PR introduce?**

  Repo settings

## **For any code change,**

- [x] Related documentation has been updated if needed
- [x] Related tests have been updated or tests have been added

## **Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

## **Tested in the following browsers:**

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Comment by Koooooo-7** [comment]
We have the `Google Analytics` in our site, do they the same thing? I check this doc below.

https://developers.google.cn/site-verification/v1/getting_started#site-verification-methods

**Comment by sy-records** [comment]
https://github.com/docsifyjs/docsify/commit/21336444f4481121c8032d9461787a963972a74d

Meta and file conflict?
I'll contact him and see if he can share the permissions.

**Review by sy-records — COMMENTED** [review]
@trusktr I invited you, please check your gmail. In that case, can this PR be closed?

**Comment by trusktr** [comment]
@sy-records Hey, the Google Analytics is actually different from the Search Console. Looks like this:

Screenshot 2023-01-22 at 11 31 37 AM

Screenshot 2023-01-22 at 11 05 33 PM

**Comment by sy-records** [comment]
It's been verified and I'll invite you guys.

https://github.com/js-org/js.org/issues/9079

**Pull request closed without merging**
